### ISSUE TITLE
Is there any Supplemental section in the gitlab page?

### ISSUE THREAD

**Issue by chemgeeklian** [ranganathanlab/pySCA#1]
In https://ranganathanlab.gitlab.io/pySCA/get_started/
it is indicated in section 3 that some eq. could be found in the Supplemental section. I searched for "Supplemental" but did not get any...

**Comment by sudorook** [comment]
I think it's referring to the supplementary information for one of the papers, probably the Halabi one. Some of the equations and section numbers on the website don't match, though. There are two other references at the bottom of the page, but they seem less likely...

http://ranganathanlab.org/wp-content/uploads/2018/05/Halabi_Ranganathan_SI.pdf

**Comment by sudorook** [comment]
The references to supplementary information on that page were referring to the 2016 paper, which wasn't listed at the bottom. I've now added it.

That paper and its supplements are very useful:

https://doi.org/10.1371/journal.pcbi.1004817
https://doi.org/10.1371/journal.pcbi.1004817.s001
https://doi.org/10.1371/journal.pcbi.1004817.s002
https://doi.org/10.1371/journal.pcbi.1004817.s003
https://doi.org/10.1371/journal.pcbi.1004817.s004
