### ISSUE TITLE
annotateMSA

### ISSUE THREAD

**Issue by vapourisedman** [ranganathanlab/pySCA#2]
Hi,

We download PFAM alignment and directly run in annotateMSA, but I believe there might be a problem when new annotated file was created.
All goes swimmingly, yet when we make analysis at the step pf phylogenic tree or taxonomic group -- it is giving error -- seems like the  "  '|'  " that is in the annotated database are not being read correctly.

An example error is like

***********
IndexError                                Traceback (most recent call last)
<ipython-input-5-bbc91cc9a2d8> in <module>
      8     s1 = h.split('__')
      9     s2 = s1[0].split('|')
---> 10     hs = s1[1].split('|')
     11     tax = []
     12     annot[s2[1]] = sca.Annot(s1[0], hs[2], ','.join(hs[3:-2]))

IndexError: list index out of range

***********
 
We tried this for a couple of different PFAM alignments and gave us same problem? Any suggestions?

Cheers,

Mehmet

**Comment by sudorook** [comment]
The '|'s are being read just fine. By default, the field delimiter is '|', not '__' in line 8, so what happens is that line generates a list with one entry. Thus, `s1[0]` works, but `s1[1]` fails.

If you copy code from the example notebooks and run it on your own sequences, just keep in mind that they were set up to parse alignments that were generated using older versions of the annotation script or some custom script I've never seen. For Pfam alignments generated by `annotateMSA`, the order the headers in the FASTA file is: ID/Accession #, description, species, taxonomy. The taxonomy is a comma-delimited list. Just look at the first line of one your annotated alignments for an example.

I wrote a function called `parseAlgHeader` for splitting the header into a list of those fields. It's in the repo now, and it will avoid issues that could arise if the "|" delimiter shows up in the description field in your annotated alignments. Basically,

```
from pysca import scaTools as sca

hd, seq = sca.readAlg(<your file>)

hd_fields = sca.parseAlgHeader(hd[0]) # get header for first sequence
print(hd[0]) # id
print(hd[1]) # protein description
print(hd[2]) # species
print(hd[3]) # taxonomic groups (top to bottom, comma-delimited)
```
As far as the rest of the phylogeny analysis goes, the notebooks for DHFR and beta lactamase will likely be more helpful.
